export const dummyFlights = [
    {
        airline: "Philippines Airline",
        code: "PA - 5620",
        travelClass: "Economy",
        price: 18500,
        refundable: true,
        flightDetails: "Includes 1 free baggage, in-flight meal, and seat selection.",
        departureAirport: "Mumbai",
        arrivalAirport: "New York",
        stops: {
            onward: 1,
            return: 0
        },
        timings: {
            departTime: "14:50",
            arriveTime: "07:35",
            duration: "10hr 35min",
            departDate: "Sun, 29 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "BOM - Terminal 2\nMumbai, India",
            to: "JFK - Terminal 2\nNew York, USA",
        },
    },
    {
        airline: "Blogzine Airline",
        code: "FFR - 5682",
        travelClass: "Economy",
        price: 17500,
        refundable: false,
        flightDetails: "No baggage included, Snacks available for purchase.",
        departureAirport: "Mumbai",
        arrivalAirport: "New York",
        stops: {
            onward: 0,
            return: 1
        },
        timings: {
            departTime: "15:10",
            arriveTime: "08:45",
            duration: "10hr 35min",
            departDate: "Sun, 29 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "BOM - Terminal 1\nMumbai, India",
            to: "JFK - Terminal 4\nNew York, USA",
        },
    },
    {
        airline: "Wizxio Airline",
        code: "SA - 1254",
        travelClass: "Business",
        price: 29500,
        refundable: true,
        flightDetails: "Business class seating, 2 checked bags, lounge access.",
        departureAirport: "Delhi",
        arrivalAirport: "New York",
        stops: {
            onward: 0,
            return: 0
        },
        timings: {
            departTime: "16:30",
            arriveTime: "07:10",
            duration: "10hr 40min",
            departDate: "Sun, 29 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "DEL - Terminal 3\nDelhi, India",
            to: "JFK - Terminal 1\nNew York, USA",
        },
    },
    {
        airline: "Folioo Airline",
        code: "CCE - 2158",
        travelClass: "Economy",
        price: 16500,
        refundable: true,
        flightDetails: "1 carry-on bag included, seat selection with extra charge.",
        departureAirport: "Bangalore",
        arrivalAirport: "New York",
        stops: {
            onward: 2,
            return: 1
        },
        timings: {
            departTime: "18:00",
            arriveTime: "07:50",
            duration: "11hr 50min",
            departDate: "Sun, 29 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "BLR - Terminal 1\nBangalore, India",
            to: "JFK - Terminal 2\nNew York, USA",
        },
    },
    {
        airline: "Skyreach Airline",
        code: "SKR - 8821",
        travelClass: "Economy",
        price: 18000,
        refundable: false,
        flightDetails: "1 personal item only, No checked baggage.",
        departureAirport: "Hyderabad",
        arrivalAirport: "New York",
        stops: {
            onward: 1,
            return: 2
        },
        timings: {
            departTime: "21:45",
            arriveTime: "10:30",
            duration: "12hr 45min",
            departDate: "Sun, 29 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "HYD - Terminal C\nHyderabad, India",
            to: "JFK - Terminal 5\nNew York, USA",
        },
    },
    {
        airline: "BlueJet Airline",
        code: "BJT - 9347",
        travelClass: "First Class",
        price: 22000,
        refundable: true,
        flightDetails: "Includes 2 bags, priority boarding, refundable ticket.",
        departureAirport: "Kolkata",
        arrivalAirport: "New York",
        stops: {
            onward: 0,
            return: 0
        },
        timings: {
            departTime: "10:20",
            arriveTime: "23:00",
            duration: "12hr 40min",
            departDate: "Mon, 30 Jan 2025",
            arriveDate: "Mon, 30 Jan 2025",
            from: "CCU - Terminal 2\nKolkata, India",
            to: "JFK - Terminal 1\nNew York, USA",
        },
    },
    {
        airline: "Nimbus Airline",
        code: "NMB - 2231",
        travelClass: "Business",
        price: 32000,
        refundable: true,
        flightDetails: "Business cabin, in-flight wifi, extra legroom, full meal.",
        departureAirport: "Chennai",
        arrivalAirport: "New York",
        stops: {
            onward: 1,
            return: 0
        },
        timings: {
            departTime: "23:50",
            arriveTime: "12:30",
            duration: "12hr 40min",
            departDate: "Mon, 30 Jan 2025",
            arriveDate: "Tue, 31 Jan 2025",
            from: "MAA - Terminal 1\nChennai, India",
            to: "JFK - Terminal 1\nNew York, USA",
        },
    },
    {
        airline: "Astra Airways",
        code: "ASA - 6124",
        travelClass: "Economy",
        price: 15900,
        refundable: false,
        flightDetails: "Basic economy, Seat assigned at check-in.",
        departureAirport: "Ahmedabad",
        arrivalAirport: "New York",
        stops: {
            onward: 0,
            return: 1
        },
        timings: {
            departTime: "01:20",
            arriveTime: "12:45",
            duration: "11hr 25min",
            departDate: "Tue, 31 Jan 2025",
            arriveDate: "Tue, 31 Jan 2025",
            from: "AMD - Terminal 1\nAhmedabad, India",
            to: "JFK - Terminal 4\nNew York, USA",
        },
    },
    {
        airline: "Altura Airline",
        code: "ALT - 7779",
        travelClass: "Business",
        price: 29900,
        refundable: true,
        flightDetails: "Lie-flat seat, 3-course meal, premium lounge access.",
        departureAirport: "Goa",
        arrivalAirport: "New York",
        stops: {
            onward: 2,
            return: 2
        },
        timings: {
            departTime: "03:30",
            arriveTime: "15:10",
            duration: "11hr 40min",
            departDate: "Tue, 31 Jan 2025",
            arriveDate: "Tue, 31 Jan 2025",
            from: "GOI - Terminal 2\nGoa, India",
            to: "JFK - Terminal 1\nNew York, USA",
        },
    },
    {
        airline: "Velocia Express",
        code: "VEX - 9900",
        travelClass: "Economy",
        price: 17800,
        refundable: false,
        flightDetails: "Economy seating, 1 snack, no checked bag.",
        departureAirport: "Pune",
        arrivalAirport: "New York",
        stops: {
            onward: 1,
            return: 1
        },
        timings: {
            departTime: "05:10",
            arriveTime: "16:00",
            duration: "10hr 50min",
            departDate: "Tue, 31 Jan 2025",
            arriveDate: "Tue, 31 Jan 2025",
            from: "PNQ - Terminal 1\nPune, India",
            to: "JFK - Terminal 5\nNew York, USA",
        },
    },
];